/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pantallas;

import dtos.IngredienteDTO;
import dtos.IngredienteEnProductoDTO;
import dtos.PedidoDTO;
import dtos.ProductoDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author valeria
 */
public class DlgModificarProducto extends javax.swing.JDialog {

    private String idProductoActual;
    private float precioProductoActual;
    private Integer tiempoPreparacionActual;
    private PedidoDTO resultado;
    private List<JCheckBox> checksIngredientes = new ArrayList<>();

    public DlgModificarProducto(java.awt.Frame parent, ProductoDTO producto, List<IngredienteEnProductoDTO> ingredientesRemovibles, PedidoDTO pedidoExistente) {
        super(parent, true);
        initComponents();
        // System.out.println("ID RECIBIDO: " + producto.getId());
        this.idProductoActual = producto.getId();
        this.precioProductoActual = producto.getPrecio();
        lblNombreProducto.setText(producto.getNombre());
        configurarPanelIngredientes(ingredientesRemovibles);
        cargarIngredientesSeleccionados(pedidoExistente);
        this.setLocationRelativeTo(null);
    }

    private void configurarPanelIngredientes(List<IngredienteEnProductoDTO> ingredientes) {
        pnlListaIngredientes.setLayout(new BoxLayout(pnlListaIngredientes, BoxLayout.Y_AXIS));
        pnlListaIngredientes.removeAll();
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 248, 235));

        // Label del precio
        JLabel lblPrecio = new JLabel("$" + precioProductoActual);
        lblPrecio.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        lblPrecio.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        lblPrecio.setBackground(new java.awt.Color(255, 248, 235));
        lblPrecio.setOpaque(false);

        pnlListaIngredientes.add(lblPrecio);

        // Espacio opcional
        pnlListaIngredientes.add(Box.createVerticalStrut(30));
        for (IngredienteEnProductoDTO ing : ingredientes) {

            JCheckBox check = new JCheckBox("Sin " + ing.getNombre());
            check.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
            check.setBackground(new java.awt.Color(255, 248, 235));
            check.setFont(new java.awt.Font("Segoe UI", 0, 18));
            check.setName(String.valueOf(ing.getId()));
            checksIngredientes.add(check);
            pnlListaIngredientes.add(check);
        }

        pnlListaIngredientes.revalidate();
        pnlListaIngredientes.repaint();
    }

    private void cargarIngredientesSeleccionados(PedidoDTO pedido) {

        if (pedido == null || pedido.getDescripcion() == null) {
            return;
        }

        String[] especificaciones = pedido.getDescripcion().split(",");

        for (String esp : especificaciones) {

            String texto = esp.trim();

            for (JCheckBox chk : checksIngredientes) {

                if (chk.getText().equalsIgnoreCase(texto)) {
                    chk.setSelected(true);
                }
            }
        }
    }

    public PedidoDTO getResultado() {
        return resultado;
    }

    /**
     * Creates new form DlgModificarProducto
     */
    public DlgModificarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        panelNaranja = new javax.swing.JPanel();
        lblNombreProducto = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        pnlBoton = new javax.swing.JPanel();
        btnListo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlListaIngredientes = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlContenedor.setBackground(new java.awt.Color(255, 248, 235));

        panelNaranja.setBackground(new java.awt.Color(254, 168, 0));

        lblNombreProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProducto.setText("Producto X");

        lblSalir.setFont(new java.awt.Font("Hiragino Sans", 1, 24)); // NOI18N
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNaranjaLayout = new javax.swing.GroupLayout(panelNaranja);
        panelNaranja.setLayout(panelNaranjaLayout);
        panelNaranjaLayout.setHorizontalGroup(
            panelNaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNaranjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaranjaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSalir)
                .addGap(22, 22, 22))
        );
        panelNaranjaLayout.setVerticalGroup(
            panelNaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaranjaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSalir)
                .addGap(26, 26, 26)
                .addComponent(lblNombreProducto)
                .addGap(81, 81, 81))
        );

        pnlBoton.setBackground(new java.awt.Color(255, 248, 235));

        btnListo.setBackground(new java.awt.Color(44, 44, 44));
        btnListo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnListo.setForeground(new java.awt.Color(255, 255, 255));
        btnListo.setText("Listo");
        btnListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListoMouseClicked(evt);
            }
        });
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonLayout = new javax.swing.GroupLayout(pnlBoton);
        pnlBoton.setLayout(pnlBotonLayout);
        pnlBotonLayout.setHorizontalGroup(
            pnlBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        pnlBotonLayout.setVerticalGroup(
            pnlBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListo)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlListaIngredientes.setBackground(new java.awt.Color(255, 248, 235));
        pnlListaIngredientes.setFont(new java.awt.Font("Muna", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlListaIngredientesLayout = new javax.swing.GroupLayout(pnlListaIngredientes);
        pnlListaIngredientes.setLayout(pnlListaIngredientesLayout);
        pnlListaIngredientesLayout.setHorizontalGroup(
            pnlListaIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlListaIngredientesLayout.setVerticalGroup(
            pnlListaIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlListaIngredientes);

        jPanel2.setBackground(new java.awt.Color(255, 248, 235));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNaranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addComponent(panelNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListoMouseClicked

    }//GEN-LAST:event_btnListoMouseClicked

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        StringBuilder especificaciones = new StringBuilder();

        for (JCheckBox chk : checksIngredientes) {
            if (chk.isSelected()) {
                especificaciones.append(chk.getText()).append(", ");
            }
        }

        if (especificaciones.length() > 0) {
            especificaciones.setLength(especificaciones.length() - 2);
        }

        resultado = new PedidoDTO();
        resultado.setIdProducto(idProductoActual);
        resultado.setNombreProducto(lblNombreProducto.getText());
        resultado.setCantidad(1);
        resultado.setDescripcion(especificaciones.toString());
        resultado.setPrecioProducto(precioProductoActual);

        this.dispose();
    }//GEN-LAST:event_btnListoActionPerformed

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        dispose();
    }//GEN-LAST:event_lblSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JPanel panelNaranja;
    private javax.swing.JPanel pnlBoton;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlListaIngredientes;
    // End of variables declaration//GEN-END:variables
}
