/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pantallas;

/**
 *
 * @author valeria
 */
public class DlgPagoTarjeta extends javax.swing.JDialog {

    /**
     * Creates new form DlgPagoTarjeta
     */
    public DlgPagoTarjeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPagoTarjeta = new javax.swing.JPanel();
        lblTituloPagoTarjeta = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        lblAPagar = new javax.swing.JLabel();
        lblSimbolo1 = new javax.swing.JLabel();
        txtMontoAPAgar = new javax.swing.JTextField();
        btnConectarTerminal = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        lblEstatus = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        separator3 = new javax.swing.JSeparator();
        lblPagado = new javax.swing.JLabel();
        lblRestante = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPagoTarjeta.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloPagoTarjeta.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblTituloPagoTarjeta.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloPagoTarjeta.setText("Pago con Tarjeta");

        lblAPagar.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblAPagar.setText("Monto a Pagar:");

        lblSimbolo1.setText("$");

        txtMontoAPAgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoAPAgarActionPerformed(evt);
            }
        });

        btnConectarTerminal.setBackground(new java.awt.Color(153, 153, 153));
        btnConectarTerminal.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnConectarTerminal.setForeground(new java.awt.Color(255, 255, 255));
        btnConectarTerminal.setText("CONECTAR TERMINAL");
        btnConectarTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarTerminalActionPerformed(evt);
            }
        });

        lblEstatus.setFont(new java.awt.Font("Telugu Sangam MN", 0, 13)); // NOI18N
        lblEstatus.setText("Estatus: Null");

        lblFolio.setFont(new java.awt.Font("Telugu Sangam MN", 0, 13)); // NOI18N
        lblFolio.setText("Folio: Null");

        lblPagado.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblPagado.setText("Total Pagado con Tarjeta: $XXX.XXX");

        lblRestante.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblRestante.setText("Total Restante: $XXX.XXX");

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPagoTarjetaLayout = new javax.swing.GroupLayout(pnlPagoTarjeta);
        pnlPagoTarjeta.setLayout(pnlPagoTarjetaLayout);
        pnlPagoTarjetaLayout.setHorizontalGroup(
            pnlPagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoTarjetaLayout.createSequentialGroup()
                .addGroup(pnlPagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagoTarjetaLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnConectarTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPagoTarjetaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(pnlPagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPagado)
                            .addGroup(pnlPagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEstatus)
                                .addGroup(pnlPagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPagoTarjetaLayout.createSequentialGroup()
                                        .addComponent(lblAPagar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblSimbolo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMontoAPAgar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblFolio)
                                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRestante)
                            .addComponent(btnContinuar))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoTarjetaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloPagoTarjeta)
                .addGap(144, 144, 144))
        );
        pnlPagoTarjetaLayout.setVerticalGroup(
            pnlPagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoTarjetaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloPagoTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPagar)
                    .addComponent(lblSimbolo1)
                    .addComponent(txtMontoAPAgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnConectarTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFolio)
                .addGap(18, 18, 18)
                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPagado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPagoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPagoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoAPAgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoAPAgarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoAPAgarActionPerformed

    private void btnConectarTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarTerminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConectarTerminalActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPagoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPagoTarjeta dialog = new DlgPagoTarjeta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarTerminal;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel lblAPagar;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblPagado;
    private javax.swing.JLabel lblRestante;
    private javax.swing.JLabel lblSimbolo1;
    private javax.swing.JLabel lblTituloPagoTarjeta;
    private javax.swing.JPanel pnlPagoTarjeta;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JTextField txtMontoAPAgar;
    // End of variables declaration//GEN-END:variables
}
