/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pantallas;

import coordinador.CoordinadorInterfaces;
import dtos.ComandaDTO;
import dtos.ResultadoPagoDTO;
import dtos.SolicitudPagoDTO;
import entidades.DetallePagoCodi;
import enums.MetodoPago;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author valeria
 */
public class DlgPagoCodi extends javax.swing.JDialog {
    private final ComandaDTO comanda;

    private float restante;

    private ResultadoPagoDTO resultadoPago;

    private final DlgPagoComanda dlgPadre;

    private final CoordinadorInterfaces coordinador;

    /**
     * Creates new form DlgPagoCodi
     */
    public DlgPagoCodi(java.awt.Frame parent, boolean modal, ComandaDTO comanda, float restante, DlgPagoComanda dlgPadre, CoordinadorInterfaces coordinador) {
        super(parent, modal);
        initComponents();
        
        this.comanda = comanda;
        this.restante = restante;
        this.dlgPadre = dlgPadre;
        this.coordinador = coordinador;
        
        inicializarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPagoCodi = new javax.swing.JPanel();
        lblTituloPagoCodi = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        lblAPagarCodi = new javax.swing.JLabel();
        lblSimbolo = new javax.swing.JLabel();
        txtMontoAPagar = new javax.swing.JTextField();
        btnGenerarQR = new javax.swing.JButton();
        lblTituloInformacionPago = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        lblEstatus = new javax.swing.JLabel();
        lblFolioPago = new javax.swing.JLabel();
        lblQR = new javax.swing.JLabel();
        separator3 = new javax.swing.JSeparator();
        lblPagadoCodi = new javax.swing.JLabel();
        lblRestantePago = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPagoCodi.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloPagoCodi.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblTituloPagoCodi.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloPagoCodi.setText("Pago con CoDi");

        lblAPagarCodi.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblAPagarCodi.setText("Monto a Pagar:");

        lblSimbolo.setText("$");

        txtMontoAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoAPagarActionPerformed(evt);
            }
        });

        btnGenerarQR.setBackground(new java.awt.Color(153, 153, 153));
        btnGenerarQR.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnGenerarQR.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarQR.setText("CONECTAR CODI");
        btnGenerarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarQRActionPerformed(evt);
            }
        });

        lblTituloInformacionPago.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblTituloInformacionPago.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloInformacionPago.setText("Información de Pago");

        lblEstatus.setFont(new java.awt.Font("Telugu Sangam MN", 0, 13)); // NOI18N
        lblEstatus.setText("Estatus: Null");

        lblFolioPago.setFont(new java.awt.Font("Telugu Sangam MN", 0, 13)); // NOI18N
        lblFolioPago.setText("Folio: Null");

        lblQR.setFont(new java.awt.Font("Telugu Sangam MN", 0, 13)); // NOI18N
        lblQR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQR.setText("QR:");
        lblQR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPagadoCodi.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblPagadoCodi.setText("Total Pagado con Tarjeta: $XXX.XXX");

        lblRestantePago.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblRestantePago.setText("Total Restante: $XXX.XXX");

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPagoCodiLayout = new javax.swing.GroupLayout(pnlPagoCodi);
        pnlPagoCodi.setLayout(pnlPagoCodiLayout);
        pnlPagoCodiLayout.setHorizontalGroup(
            pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoCodiLayout.createSequentialGroup()
                .addGroup(pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagoCodiLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnGenerarQR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPagoCodiLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPagadoCodi)
                            .addGroup(pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEstatus)
                                .addGroup(pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPagoCodiLayout.createSequentialGroup()
                                        .addComponent(lblAPagarCodi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblSimbolo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblFolioPago)
                                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoCodiLayout.createSequentialGroup()
                                    .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)))
                            .addComponent(lblRestantePago)
                            .addComponent(btnContinuar))))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoCodiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoCodiLayout.createSequentialGroup()
                        .addComponent(lblTituloPagoCodi)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoCodiLayout.createSequentialGroup()
                        .addComponent(lblTituloInformacionPago)
                        .addGap(146, 146, 146))))
        );
        pnlPagoCodiLayout.setVerticalGroup(
            pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoCodiLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloPagoCodi)
                .addGap(18, 18, 18)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPagoCodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPagarCodi)
                    .addComponent(lblSimbolo)
                    .addComponent(txtMontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnGenerarQR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblTituloInformacionPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFolioPago)
                .addGap(18, 18, 18)
                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPagadoCodi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestantePago)
                .addGap(31, 31, 31)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPagoCodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPagoCodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoAPagarActionPerformed

    private void btnGenerarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarQRActionPerformed
        try {
            float montoPagar = Float.parseFloat(txtMontoAPagar.getText());

            SolicitudPagoDTO solicitud = new SolicitudPagoDTO(
                comanda.getId(),
                MetodoPago.CODI,
                montoPagar,
                null
            );

            resultadoPago = coordinador.registrarPago(solicitud);

            if (resultadoPago == null || !resultadoPago.isAprobado()) {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el pago.");
                return;
            }

            DetallePagoCodi detalle =
            (DetallePagoCodi) resultadoPago.getDetallePago();

            byte[] imageBytes =
            Base64.getDecoder().decode(
                detalle.getQrBase64()
            );

            BufferedImage imagenQR =
            ImageIO.read(
                new ByteArrayInputStream(imageBytes)
            );

            Image imagenEscalada =
            imagenQR.getScaledInstance(
                250,
                250,
                Image.SCALE_SMOOTH
            );

            lblQR.setIcon(
                new ImageIcon(imagenEscalada)
            );

            lblEstatus.setText("Estatus: " + resultadoPago.getMensaje());
            lblFolioPago.setText("Folio: " + detalle.getFolio());

            lblPagadoCodi.setText("Total Pagado con CoDi: $" + resultadoPago.getMontoPagado());
            lblRestantePago.setText("Total Restante: $" + resultadoPago.getSaldoRestante());

            dlgPadre.agregarPago(resultadoPago);

            btnContinuar.setEnabled(true);
            btnGenerarQR.setEnabled(false);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingresa un monto válido.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnGenerarQRActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnGenerarQR;
    private javax.swing.JLabel lblAPagarCodi;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFolioPago;
    private javax.swing.JLabel lblPagadoCodi;
    private javax.swing.JLabel lblQR;
    private javax.swing.JLabel lblRestantePago;
    private javax.swing.JLabel lblSimbolo;
    private javax.swing.JLabel lblTituloInformacionPago;
    private javax.swing.JLabel lblTituloPagoCodi;
    private javax.swing.JPanel pnlPagoCodi;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JTextField txtMontoAPagar;
    // End of variables declaration//GEN-END:variables

    private void inicializarPantalla() {
        txtMontoAPagar.setText("");
        
        lblEstatus.setText("");
        lblFolioPago.setText("");
        lblQR.setText("");
        
        
        lblPagadoCodi.setText("Total Pagado con CoDi: $0.00");
        lblRestantePago.setText("Total Restante: $" + restante);

        btnContinuar.setEnabled(false);
    }
}
