/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pantallas;

import coordinador.CoordinadorInterfaces;
import dtos.ComandaDTO;
import dtos.ResultadoPagoDTO;
import dtos.SolicitudPagoDTO;
import entidades.DetallePagoEfectivo;
import enums.MetodoPago;
import javax.swing.JOptionPane;

/**
 *
 * @author valeria
 */
public class DlgPagoEfectivo extends javax.swing.JDialog {
    private final ComandaDTO comanda;

    private float restante;

    private ResultadoPagoDTO resultadoPago;

    private final DlgPagoComanda dlgPadre;

    private final CoordinadorInterfaces coordinador;
    
    /**
     * Creates new form DlgPagoEfectivo
     */
    public DlgPagoEfectivo(java.awt.Frame parent, boolean modal, ComandaDTO comanda, float restante, DlgPagoComanda dlgPadre, CoordinadorInterfaces coordinador) {
        super(parent, modal);
        initComponents();

        this.comanda = comanda;
        this.restante = restante;
        this.dlgPadre = dlgPadre;
        this.coordinador = coordinador;
        
        inicializarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPagoEfectivo = new javax.swing.JPanel();
        lblTituloPagoEfectivo = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        lblAPagar = new javax.swing.JLabel();
        lblEntregado = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblSimbolo1 = new javax.swing.JLabel();
        lblSimbolo2 = new javax.swing.JLabel();
        lblSimbolo3 = new javax.swing.JLabel();
        txtMontoAPAgar = new javax.swing.JTextField();
        txtMontoEntregado = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        lblPagado = new javax.swing.JLabel();
        lblRestante = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPagoEfectivo.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloPagoEfectivo.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblTituloPagoEfectivo.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloPagoEfectivo.setText("Pago en Efectivo");

        lblAPagar.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblAPagar.setText("Monto a Pagar:");

        lblEntregado.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblEntregado.setText("Monto Entregado:");

        lblCambio.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblCambio.setText("Cambio:");

        lblSimbolo1.setText("$");

        lblSimbolo2.setText("$");

        lblSimbolo3.setText("$");

        txtMontoAPAgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoAPAgarActionPerformed(evt);
            }
        });

        txtCambio.setEnabled(false);

        btnAceptar.setBackground(new java.awt.Color(153, 153, 153));
        btnAceptar.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblPagado.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblPagado.setText("Total Pagado en Efectivo: $XXX.XXX");

        lblRestante.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        lblRestante.setText("Total Restante: $XXX.XXX");

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblAtras.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        lblAtras.setText("X");

        javax.swing.GroupLayout pnlPagoEfectivoLayout = new javax.swing.GroupLayout(pnlPagoEfectivo);
        pnlPagoEfectivo.setLayout(pnlPagoEfectivoLayout);
        pnlPagoEfectivoLayout.setHorizontalGroup(
            pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoEfectivoLayout.createSequentialGroup()
                            .addComponent(lblTituloPagoEfectivo)
                            .addGap(153, 153, 153))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoEfectivoLayout.createSequentialGroup()
                            .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                            .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                                    .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAPagar)
                                        .addComponent(lblEntregado)
                                        .addComponent(lblCambio))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                                            .addComponent(lblSimbolo2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtMontoEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                                            .addComponent(lblSimbolo1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtMontoAPAgar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                                            .addComponent(lblSimbolo3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))))
                                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPagado)
                                .addComponent(lblRestante)
                                .addComponent(btnContinuar))
                            .addGap(65, 65, 65)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagoEfectivoLayout.createSequentialGroup()
                        .addComponent(lblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlPagoEfectivoLayout.setVerticalGroup(
            pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoEfectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAtras)
                .addGap(2, 2, 2)
                .addComponent(lblTituloPagoEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPagar)
                    .addComponent(lblSimbolo1)
                    .addComponent(txtMontoAPAgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntregado)
                    .addComponent(lblSimbolo2)
                    .addComponent(txtMontoEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlPagoEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCambio)
                    .addComponent(lblSimbolo3)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPagado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRestante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPagoEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPagoEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoAPAgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoAPAgarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoAPAgarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            float montoPagar = Float.parseFloat(txtMontoAPAgar.getText());
            float montoEntregado = Float.parseFloat(txtMontoEntregado.getText());

            DetallePagoEfectivo detalle = new DetallePagoEfectivo(
                    montoEntregado,
                    0
            );

            SolicitudPagoDTO solicitud = new SolicitudPagoDTO(
                    comanda.getId(),
                    MetodoPago.EFECTIVO,
                    montoPagar,
                    detalle
            );

            resultadoPago = coordinador.registrarPago(solicitud);
            
            if (resultadoPago == null || !resultadoPago.isAprobado()) {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el pago.");
                return;
            }
            
            dlgPadre.agregarPago(resultadoPago);

            DetallePagoEfectivo detalleResultado =
                    (DetallePagoEfectivo) resultadoPago.getDetallePago();

            txtCambio.setText(String.valueOf(detalleResultado.getCambio()));

            lblPagado.setText(
                    "Total Pagado en Efectivo: $" + resultadoPago.getMontoPagado()
            );

            lblRestante.setText(
                    "Total Restante: $" + resultadoPago.getSaldoRestante()
            );

            btnContinuar.setEnabled(true);
            btnAceptar.setEnabled(false);
            
            

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingresa montos válidos.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel lblAPagar;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblEntregado;
    private javax.swing.JLabel lblPagado;
    private javax.swing.JLabel lblRestante;
    private javax.swing.JLabel lblSimbolo1;
    private javax.swing.JLabel lblSimbolo2;
    private javax.swing.JLabel lblSimbolo3;
    private javax.swing.JLabel lblTituloPagoEfectivo;
    private javax.swing.JPanel pnlPagoEfectivo;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtMontoAPAgar;
    private javax.swing.JTextField txtMontoEntregado;
    // End of variables declaration//GEN-END:variables

    private void inicializarPantalla() {
        txtMontoAPAgar.setText("");
        txtMontoEntregado.setText("");
        txtCambio.setText("");

        lblPagado.setText("Total Pagado en Efectivo: $0.00");
        lblRestante.setText("Total Restante: $" + restante);

        btnContinuar.setEnabled(false);
    }

}
