package pantallas;

import coordinador.CoordinadorInterfaces;
import dtos.ComandaDTO;
import dtos.PedidoDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Piña
 */
public class DlgResumenComanda extends javax.swing.JDialog {

    private Integer numMesa;
    private String nombreCliente;
    private List<PedidoDTO> productos;
    private CoordinadorInterfaces coordinador;

    private List<PedidoDTO> pedidosExistentes = new ArrayList<>();
    private List<PedidoDTO> pedidosNuevos = new ArrayList<>();
    private boolean modoAgregar;
    private boolean modoEdicion;
    private ComandaDTO comandaActual;

    /**
     * Creates new form DlgResumenComanda
     */
    public DlgResumenComanda(CoordinadorInterfaces coordinador, java.awt.Frame parent, List<PedidoDTO> productos, Integer numMesa, String nombreCliente) {
        super(parent, true);
        this.coordinador = coordinador;
        initComponents();
        this.pedidosNuevos = coordinador.getComandaTemporal();
        this.modoAgregar = false;
        this.numMesa = numMesa;
        this.nombreCliente = nombreCliente;

        configurarListaPedidos();
        this.setLocationRelativeTo(null);
    }

    public DlgResumenComanda(
            CoordinadorInterfaces coordinador,
            java.awt.Frame parent,
            List<PedidoDTO> pedidosExistentes,
            List<PedidoDTO> pedidosNuevos,
            Integer numMesa,
            String nombreCliente,
            boolean modoAgregar,
            ComandaDTO comandaActual
    ) {
        super(parent, true);

        this.coordinador = coordinador;
        this.pedidosExistentes = pedidosExistentes;
        this.pedidosNuevos = pedidosNuevos;
        this.numMesa = numMesa;
        this.nombreCliente = nombreCliente;
        this.modoAgregar = modoAgregar;
        this.comandaActual = comandaActual;

        initComponents();

        configurarListaPedidos();

        setMesaAndCliente(numMesa, nombreCliente);

        this.setLocationRelativeTo(null);
    }

    public DlgResumenComanda(
            CoordinadorInterfaces coordinador,
            java.awt.Frame parent,
            ComandaDTO comandaEdicion,
            List<PedidoDTO> pedidosNuevos) {
        super(parent, true);
        this.coordinador = coordinador;
        // Los pedidos existentes son los que quedaron en la comanda tras quitar/modificar
        this.pedidosExistentes = new ArrayList<>(comandaEdicion.getPedidos());
        this.pedidosNuevos = pedidosNuevos != null ? pedidosNuevos : new ArrayList<>();
        this.numMesa = comandaEdicion.getNumMesa();
        this.nombreCliente = comandaEdicion.getNombreCliente();
        this.modoAgregar = false;
        this.modoEdicion = true; // <-- modo edición
        this.comandaActual = comandaEdicion;
        initComponents();
        configurarListaPedidos();
        setMesaAndCliente(comandaEdicion.getNumMesa(), comandaEdicion.getNombreCliente());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreMesa = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        pnlListaProductos = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 248, 235));

        jPanel1.setBackground(new java.awt.Color(255, 248, 235));

        lblNombreMesa.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblNombreMesa.setForeground(new java.awt.Color(153, 102, 0));
        lblNombreMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreMesa.setText("Mesa x");

        lblNombreCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(153, 102, 0));
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setText("Resumen comanda x");

        pnlListaProductos.setBackground(new java.awt.Color(255, 248, 235));
        pnlListaProductos.setFont(new java.awt.Font("Muna", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlListaProductosLayout = new javax.swing.GroupLayout(pnlListaProductos);
        pnlListaProductos.setLayout(pnlListaProductosLayout);
        pnlListaProductosLayout.setHorizontalGroup(
            pnlListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlListaProductosLayout.setVerticalGroup(
            pnlListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(pnlListaProductos);

        btnConfirmar.setBackground(new java.awt.Color(44, 44, 44));
        btnConfirmar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNombreMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNombreMesa)
                .addGap(26, 26, 26)
                .addComponent(lblNombreCliente)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed


    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        if (modoEdicion) {
            coordinador.actualizarComanda(comandaActual, pedidosNuevos);

        } else if (modoAgregar) {
            if (pedidosNuevos == null || pedidosNuevos.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debes agregar al menos un pedido nuevo",
                        "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
            coordinador.agregarPedidosAComanda(comandaActual, pedidosNuevos);

        } else {
            // NUEVA comanda — usa los pedidosNuevos
            if (pedidosNuevos == null || pedidosNuevos.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debes agregar al menos un pedido",
                        "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
            coordinador.enviarComandaAFinal(nombreCliente, numMesa, pedidosNuevos); 
        }

    }//GEN-LAST:event_btnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreMesa;
    private javax.swing.JPanel pnlListaProductos;
    // End of variables declaration//GEN-END:variables

    public void setMesaAndCliente(Integer numMesa, String cliente) {

        lblNombreMesa.setText("Mesa " + numMesa);
        lblNombreCliente.setText("Resumen comanda: " + cliente);
    }

    private void configurarListaPedidos() {

        pnlListaProductos.setLayout(
                new javax.swing.BoxLayout(
                        pnlListaProductos,
                        javax.swing.BoxLayout.Y_AXIS
                )
        );

        pnlListaProductos.removeAll();

        // PEDIDOS EXISTENTES
        for (PedidoDTO ped : pedidosExistentes) {

            javax.swing.JLabel lbl = new javax.swing.JLabel(
                    "• " + ped.toString()
            );

            lbl.setFont(new java.awt.Font("Trebuchet MS", java.awt.Font.PLAIN, 14));

            lbl.setBorder(
                    javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)
            );

            pnlListaProductos.add(lbl);
        }

        // PEDIDOS NUEVOS
        if (pedidosNuevos != null) {
            for (PedidoDTO ped : pedidosNuevos) {

                javax.swing.JLabel lbl = new javax.swing.JLabel(
                        "• " + ped.toString()
                );

                lbl.setForeground(new java.awt.Color(0, 140, 0)); // VERDE

                lbl.setFont(
                        new java.awt.Font("Trebuchet MS", java.awt.Font.BOLD, 14)
                );

                lbl.setBorder(
                        javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)
                );

                pnlListaProductos.add(lbl);
            }
        }
        pnlListaProductos.revalidate();
        pnlListaProductos.repaint();
    }
}
