/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import control.MesaControl;
import coordinador.CoordinadorInterfaces;
import dtos.ComandaDTO;
import dtos.MesaDTO;
import dtos.PedidoDTO;
import enums.EstadoPedidoDTO;
import excepciones.MesasException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

/**
 *
 * @author Piña
 */
public class FrmPantallaComandas extends javax.swing.JFrame {

    private coordinador.CoordinadorInterfaces coordinador;
    String idMesero;

    MesaControl control = new MesaControl();

    /**
     * Creates new form FrmPantallaComandas
     *
     * @param coordinador
     */
    public FrmPantallaComandas(CoordinadorInterfaces coordinador) {
        this.coordinador = coordinador;
        this.coordinador.setFrmComandas(this);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        initComponents();
        this.setLocationRelativeTo(null);
        panMesas.setLayout(new BoxLayout(panMesas, BoxLayout.Y_AXIS));

        panComandas.revalidate();
        panComandas.repaint();
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(25);

        btnEnviarComandas.setVisible(false);
        btnPagoGeneral.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panComandas = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        btnLevantarComanda = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panMesas = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        panTituloMesas = new javax.swing.JPanel();
        lblMesas1 = new javax.swing.JLabel();
        btnEnviarComandas = new javax.swing.JButton();
        btnPagoGeneral = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        panComandasLlenas = new javax.swing.JPanel();
        lblEspacio = new javax.swing.JLabel();
        lblSeleccioneMesa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panComandas.setBackground(new java.awt.Color(255, 255, 255));

        panHeader.setBackground(new java.awt.Color(255, 202, 102));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_header.png"))); // NOI18N

        lblEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setText("Empleado X");

        btnLevantarComanda.setBackground(new java.awt.Color(255, 227, 172));
        btnLevantarComanda.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnLevantarComanda.setText("Levantar Comanda");
        btnLevantarComanda.setBorder(null);
        btnLevantarComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLevantarComandaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLevantarComandaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLevantarComandaMouseReleased(evt);
            }
        });
        btnLevantarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevantarComandaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(213, 210, 203));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton2.setText("Cerrar Sesión");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(lblEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                .addComponent(btnLevantarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpleado)
                            .addComponent(btnLevantarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panMesas.setLayout(new javax.swing.BoxLayout(panMesas, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(panMesas);

        lblMesas1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMesas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesas1.setText("MESAS");

        javax.swing.GroupLayout panTituloMesasLayout = new javax.swing.GroupLayout(panTituloMesas);
        panTituloMesas.setLayout(panTituloMesasLayout);
        panTituloMesasLayout.setHorizontalGroup(
            panTituloMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTituloMesasLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lblMesas1)
                .addGap(52, 52, 52))
        );
        panTituloMesasLayout.setVerticalGroup(
            panTituloMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloMesasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMesas1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnEnviarComandas.setBackground(new java.awt.Color(211, 255, 172));
        btnEnviarComandas.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnEnviarComandas.setText("Enviar comandas");
        btnEnviarComandas.setBorder(null);
        btnEnviarComandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarComandasMouseClicked(evt);
            }
        });
        btnEnviarComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarComandasActionPerformed(evt);
            }
        });

        btnPagoGeneral.setBackground(new java.awt.Color(132, 194, 118));
        btnPagoGeneral.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnPagoGeneral.setText("Pago");
        btnPagoGeneral.setBorder(null);
        btnPagoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoGeneralActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panComandasLlenas.setBackground(new java.awt.Color(255, 255, 255));
        panComandasLlenas.setLayout(new javax.swing.BoxLayout(panComandasLlenas, javax.swing.BoxLayout.Y_AXIS));

        lblEspacio.setFont(new java.awt.Font("Segoe UI", 0, 150)); // NOI18N
        lblEspacio.setForeground(new java.awt.Color(255, 255, 255));
        lblEspacio.setText("0");
        panComandasLlenas.add(lblEspacio);

        lblSeleccioneMesa.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblSeleccioneMesa.setForeground(new java.awt.Color(204, 204, 204));
        lblSeleccioneMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccioneMesa.setText("         Seleccione una mesa");
        panComandasLlenas.add(lblSeleccioneMesa);

        jScrollPane3.setViewportView(panComandasLlenas);

        javax.swing.GroupLayout panComandasLayout = new javax.swing.GroupLayout(panComandas);
        panComandas.setLayout(panComandasLayout);
        panComandasLayout.setHorizontalGroup(
            panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panComandasLayout.createSequentialGroup()
                .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panComandasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComandasLayout.createSequentialGroup()
                        .addContainerGap(609, Short.MAX_VALUE)
                        .addComponent(btnEnviarComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(panTituloMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panComandasLayout.setVerticalGroup(
            panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComandasLayout.createSequentialGroup()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panTituloMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panComandasLayout.createSequentialGroup()
                        .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panComandasLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviarComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane2.setViewportView(panComandas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLevantarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevantarComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLevantarComandaActionPerformed

    private void btnLevantarComandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLevantarComandaMousePressed

        btnLevantarComanda.setFocusPainted(false);
        btnLevantarComanda.setContentAreaFilled(false);
        btnLevantarComanda.setOpaque(true);

        btnLevantarComanda.setBackground(Color.decode("#F3AE29"));
        btnLevantarComanda.setBorder(BorderFactory.createLineBorder(Color.decode("#C79A42"), 2));
    }//GEN-LAST:event_btnLevantarComandaMousePressed

    private void btnLevantarComandaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLevantarComandaMouseReleased
        btnLevantarComanda.setBackground(Color.decode("#FFE3AC"));
        btnLevantarComanda.setBorder(null);
    }//GEN-LAST:event_btnLevantarComandaMouseReleased

    private void btnLevantarComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLevantarComandaMouseClicked
        if (mesaSeleccionada != null) {
            coordinador.mostrarRegistrarCliente(mesaSeleccionada);
        } else {
            System.out.println("Selecciona una mesa primero");
        }

        this.setVisible(false);
    }//GEN-LAST:event_btnLevantarComandaMouseClicked

    private void btnEnviarComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarComandasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarComandasActionPerformed

    private void btnPagoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagoGeneralActionPerformed

    private void btnEnviarComandasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarComandasMouseClicked
        JOptionPane.showMessageDialog(this, "Comandas enviadas a cocina", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEnviarComandasMouseClicked

    public void quitarLabels() {
        lblSeleccioneMesa.setVisible(false);
        lblEspacio.setVisible(false);
    }

    public void botonesVisibles() {
        btnPagoGeneral.setVisible(true);
        btnEnviarComandas.setVisible(false);
        btnLevantarComanda.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarComandas;
    private javax.swing.JButton btnLevantarComanda;
    private javax.swing.JButton btnPagoGeneral;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblEspacio;
    private javax.swing.JLabel lblMesas1;
    private javax.swing.JLabel lblSeleccioneMesa;
    private javax.swing.JPanel panComandas;
    private javax.swing.JPanel panComandasLlenas;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel panMesas;
    private javax.swing.JPanel panTituloMesas;
    // End of variables declaration//GEN-END:variables
    private JButton btnSeleccionado = null;
    private MesaDTO mesaSeleccionada = null;

    public void cargarMesas() {
        panMesas.removeAll();
        btnLevantarComanda.setVisible(false);
        List<MesaDTO> mesas = new ArrayList<>();

        try {
            mesas = control.obtenerMesasPorMesero(String.valueOf(idMesero));
        } catch (MesasException ex) {
            System.out.println("Error al obtener mesas: " + ex.getMessage());
        }
        List<Integer> mesasConComandasListas = coordinador.obtenerMesasConComandasListas();
        mesas.sort((m1, m2) -> {
            boolean m1Lista = mesasConComandasListas.contains(m1.getNumeroMesa());

            boolean m2Lista = mesasConComandasListas.contains(m2.getNumeroMesa());

            if (m1Lista && !m2Lista) {
                return -1;
            }

            if (!m1Lista && m2Lista) {
                return 1;
            }

            return Integer.compare(m1.getNumeroMesa(), m2.getNumeroMesa());
        });

        for (MesaDTO mesa : mesas) {
            JButton btn = new JButton("Mesa " + mesa.getNumeroMesa());

            btn.setAlignmentX(Component.CENTER_ALIGNMENT);
            btn.setMaximumSize(new Dimension(150, 60));

            btn.setFocusPainted(false);

            btn.addActionListener(e -> {

                panComandasLlenas.remove(lblSeleccioneMesa);
                panComandasLlenas.remove(lblEspacio);
                btnLevantarComanda.setVisible(true);
                panComandas.revalidate();
                panComandas.repaint();

                if (btnSeleccionado != null) {

                    if (mesasConComandasListas.contains(mesaSeleccionada.getNumeroMesa())) {
                        btnSeleccionado.setBackground(Color.decode("#B9F6B1"));
                    } else {
                        btnSeleccionado.setBackground(Color.decode("#FFE3AC"));
                    }

                    btnSeleccionado.setFont(new Font("Arial", Font.PLAIN, 18));
                    btnSeleccionado.setBorder(null);
                }

                btn.setBackground(Color.decode("#FFD481"));
                btn.setFont(new Font("Arial", Font.BOLD, 18));
                btn.setBorder(BorderFactory.createLineBorder(Color.decode("#FFBE41"), 2));

                btnSeleccionado = btn;
                mesaSeleccionada = mesa;

                List<ComandaDTO> comandas = coordinador.getComandasDeMesa(mesa.getNumeroMesa());
                mostrarComandasDeMesa(mesa.getNumeroMesa(), comandas);
                // System.out.println("Seleccionaste Mesa " + mesa);
            });

            if (mesaSeleccionada != null && mesa.getNumeroMesa() == mesaSeleccionada.getNumeroMesa()) {
                btn.setBackground(Color.decode("#FFD481"));
                btn.setFont(new Font("Arial", Font.BOLD, 18));
                btn.setBorder(BorderFactory.createLineBorder(Color.decode("#FFBE41"), 2));

                btnSeleccionado = btn;

                // Restaurar comportamiento de selección
                btnLevantarComanda.setVisible(true);

                List<ComandaDTO> comandas = coordinador.getComandasDeMesa(mesa.getNumeroMesa());

                mostrarComandasDeMesa(mesa.getNumeroMesa(), comandas);
            } else if (mesasConComandasListas.contains(mesa.getNumeroMesa())) {
                btn.setBackground(Color.decode("#B9F6B1"));
                btn.setFont(new Font("Arial", Font.PLAIN, 18));
                btn.setBorder(null);
            } else {
                btn.setBackground(Color.decode("#FFE3AC"));
                btn.setFont(new Font("Arial", Font.PLAIN, 18));
                btn.setBorder(null);
            }

            panMesas.add(btn);
            panMesas.add(Box.createVerticalStrut(28));
        }

        panMesas.revalidate();
        panMesas.repaint();
    }
    private JPanel contenedorComandas;

    public void mostrarComandasDeMesa(int numeroMesa, List<ComandaDTO> comandas) {

        panComandasLlenas.removeAll();

        if (comandas == null || comandas.isEmpty()) {
            lblSeleccioneMesa.setVisible(true);
            lblEspacio.setVisible(true);
            btnEnviarComandas.setVisible(false);
            btnPagoGeneral.setVisible(false);
        } else {
            lblSeleccioneMesa.setVisible(false);
            lblEspacio.setVisible(false);

            comandas.sort((c1, c2) -> {
                boolean c1Lista = tienePedidosListos(c1);
                boolean c2Lista = tienePedidosListos(c2);

                if (c1Lista && !c2Lista) {
                    return -1;
                }

                if (!c1Lista && c2Lista) {
                    return 1;
                }

                return 0;
            });

            for (ComandaDTO c : comandas) {
                panComandasLlenas.add(new ComandaCard(c));
                panComandasLlenas.add(Box.createVerticalStrut(10));
            }
            btnEnviarComandas.setVisible(false);
            btnPagoGeneral.setVisible(true);
        }

        panComandasLlenas.revalidate();
        panComandasLlenas.repaint();
    }

    private boolean tienePedidosListos(ComandaDTO comanda) {
        for (PedidoDTO pedido : comanda.getPedidos()) {
            if (pedido.getEstado() == EstadoPedidoDTO.LISTA) {
                return true;
            }
        }
        return false;
    }

    public class ComandaCard extends JPanel {

        public ComandaCard(ComandaDTO comanda) {
            setLayout(new BorderLayout());
            setBorder(BorderFactory.createLineBorder(Color.ORANGE, 2, true));
            setBackground(Color.WHITE);
            setAlignmentX(Component.LEFT_ALIGNMENT);

            JPanel header = new JPanel(new BorderLayout());

            if (tienePedidosListos(comanda)) {
                header.setBackground(Color.decode("#B9F6B1"));
            } else {
                header.setBackground(Color.decode("#FFDA92"));
            }
            header.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

            JLabel lblTitulo = new JLabel(comanda.getNombreCliente().toUpperCase() + ": " + comanda.getEstado() + " | $" + comanda.getTotal());
            lblTitulo.setFont(new Font("Arial", Font.BOLD, 14));

            JButton btnPago = new JButton("Pago");
            btnPago.setBackground(Color.decode("#FFB21D"));
            btnPago.setPreferredSize(new Dimension(80, 30));
            btnPago.setFocusPainted(false);

            header.add(lblTitulo, BorderLayout.WEST);
            header.add(btnPago, BorderLayout.EAST);

            JPanel panelPedidos = new JPanel();
            panelPedidos.setLayout(new BoxLayout(panelPedidos, BoxLayout.Y_AXIS));
            panelPedidos.setBackground(Color.decode("#D9D9D9"));

            for (PedidoDTO ped : comanda.getPedidos()) {

                JLabel lblPedido = new JLabel();

                String texto = "• " + ped.getNombreProducto();

                if (ped.getDescripcion() != null
                        && !ped.getDescripcion().trim().isEmpty()) {

                    texto += " (" + ped.getDescripcion() + ")";
                }
                
                String estadoTexto = ped.getEstado().name();

                switch (estadoTexto) {
                    case "EN_PREPARACION":
                        estadoTexto = "EN PREPARACIÓN";
                        break;

                    case "LISTA":
                        estadoTexto = "LISTO";
                        break;
                }

                lblPedido.setText(texto + " | $" + ped.getPrecioProducto() + " | " + estadoTexto);

                switch (ped.getEstado()) {
                    case PENDIENTE:
                        lblPedido.setForeground(Color.decode("#CF2C21"));
                        break;

                    case EN_PREPARACION:
                        lblPedido.setForeground(Color.decode("#FA8411"));
                        break;

                    case LISTA:
                        lblPedido.setForeground(Color.decode("#2E9E48"));
                        break;

                    case ENTREGADO:
                        lblPedido.setForeground(Color.BLACK);
                        break;
                }

                lblPedido.setFont(new Font("Monospaced", Font.BOLD, 14));

                lblPedido.setBorder(
                        BorderFactory.createEmptyBorder(5, 5, 5, 5)
                );

//                lblPedido.setBorder(
//                        BorderFactory.createLineBorder(Color.ORANGE, 1)
//                );
                lblPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                // Hover bonito
                lblPedido.addMouseListener(new java.awt.event.MouseAdapter() {

                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent e) {
                        lblPedido.setOpaque(true);
                        lblPedido.setBackground(Color.decode("#CFCFCF"));
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent e) {
                        lblPedido.setOpaque(false);
                        lblPedido.setBackground(null);
                    }

                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent e) {

                        DlgDetallePedido dlg
                                = new DlgDetallePedido(
                                        null,
                                        true,
                                        ped,
                                        coordinador
                                );

                        dlg.setVisible(true);
                    }
                });

                panelPedidos.add(lblPedido);
            }

            JPanel body = new JPanel(new BorderLayout());
            body.setBackground(Color.decode("#D9D9D9"));
            body.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
            JScrollPane scrollPedidos = new JScrollPane(panelPedidos);
            scrollPedidos.setBorder(null);
            scrollPedidos.setHorizontalScrollBarPolicy(
                    JScrollPane.HORIZONTAL_SCROLLBAR_NEVER
            );
            scrollPedidos.setVerticalScrollBarPolicy(
                    JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED
            );

            scrollPedidos.getVerticalScrollBar().setUnitIncrement(12);

            body.add(scrollPedidos, BorderLayout.CENTER);

            JLabel lblNota = new JLabel("Selecciona un pedido para ver su detalle");
            lblNota.setFont(new Font("Arial", Font.ITALIC, 13));
            lblNota.setForeground(Color.GRAY);
            lblNota.setHorizontalAlignment(JLabel.CENTER);
            lblNota.setBorder(BorderFactory.createEmptyBorder(15, 0, 0, 0));

            body.add(lblNota, BorderLayout.SOUTH);

            JPanel footer = new JPanel(new FlowLayout(FlowLayout.RIGHT, 15, 10));
            footer.setBackground(Color.WHITE);

            JButton btnEditar = new JButton("Editar comanda");
            btnEditar.setBackground(Color.decode("#FFAD72"));
            btnEditar.setPreferredSize(new Dimension(140, 35));
            btnEditar.setFocusPainted(false);

            btnEditar.addActionListener(e -> {
                coordinador.abrirEditarComanda(comanda);
                SwingUtilities.getWindowAncestor(this).dispose();
            });

            JButton btnCancelar = new JButton("Cancelar comanda");
            btnCancelar.setBackground(Color.decode("#FF9C9C"));
            btnCancelar.setPreferredSize(new Dimension(160, 35));
            btnCancelar.setFocusPainted(false);

            JButton btnEntregar = new JButton("Entregar pedidos listos");
            btnEntregar.setBackground(Color.decode("#B9F6B1"));
            btnEntregar.setPreferredSize(new Dimension(170, 35));
            btnEntregar.setFocusPainted(false);

            btnEntregar.addActionListener(e -> {

                int confirmacion = JOptionPane.showConfirmDialog(
                        this,
                        "¿Seguro que deseas entregar pedidos listos?",
                        "Confirmar entrega",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (confirmacion == JOptionPane.YES_OPTION) {
                    try {
                        coordinador.entregarComanda(comanda.getId());

                        JOptionPane.showMessageDialog(
                                this,
                                "Comanda entregada correctamente",
                                "Éxito",
                                JOptionPane.INFORMATION_MESSAGE
                        );

                        actualizarPantalla();

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(
                                this,
                                ex.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                }
            });

            if (comanda.getEstado() != null) {

                switch (comanda.getEstado().name()) {

                    case "PENDIENTE":
                    case "EN_PREPARACION":
                    case "LISTA":
                    case "ENTREGADA":

                        footer.add(btnEditar);
                        footer.add(btnEntregar);

                        if (comanda.getEstado().name().equals("PENDIENTE")) {
                            footer.add(btnCancelar);
                        }

                        break;

                    case "PAGADA":
                        break;
                }
            }

            btnCancelar.addActionListener(e -> {

                int confirmacion = JOptionPane.showConfirmDialog(
                        this,
                        "¿Seguro que deseas cancelar esta comanda?",
                        "Confirmar cancelación",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (confirmacion == JOptionPane.YES_OPTION) {

                    try {

                        boolean eliminada = coordinador.eliminarComanda(comanda.getId());

                        if (eliminada) {

                            JOptionPane.showMessageDialog(
                                    this,
                                    "Comanda cancelada correctamente",
                                    "Éxito",
                                    JOptionPane.INFORMATION_MESSAGE
                            );

                            actualizarPantalla();

                        }

                    } catch (Exception ex) {

                        JOptionPane.showMessageDialog(
                                this,
                                ex.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                }
            });

            add(header, BorderLayout.NORTH);
            add(body, BorderLayout.CENTER);
            add(footer, BorderLayout.SOUTH);

            this.setPreferredSize(new Dimension(400, 250));
            this.setMinimumSize(new Dimension(350, 200));
            this.setMaximumSize(new Dimension(Short.MAX_VALUE, 300)); // Permite que estire a lo ancho pero no tanto a lo alto
        }
    }

    public void refrescarMesaActual() {
        if (mesaSeleccionada != null) {
            List<ComandaDTO> comandas = coordinador.getComandasDeMesa(mesaSeleccionada.getNumeroMesa());
            mostrarComandasDeMesa(mesaSeleccionada.getNumeroMesa(), comandas);
        }
    }

    public void setMesero(String id, String empleado) {
        idMesero = id;
        lblEmpleado.setText(empleado);
    }

    public void actualizarPantalla() {
        cargarMesas();
        refrescarMesaActual();
    }

}
