/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import coordinador.CoordinadorInterfaces;
import dtos.ComandaDTO;
import dtos.EmpleadoDTO;
import dtos.PedidoDTO;
import fachada.ComandaFachada;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Label;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Piña
 */
public class FrmPantallaCocina extends javax.swing.JFrame {
    
    private coordinador.CoordinadorInterfaces coordinador;
    ComandaFachada fachada = new ComandaFachada();

    /**
     * Creates new form FrmCocina
     */
    public FrmPantallaCocina(CoordinadorInterfaces coordinador, EmpleadoDTO cocina) {
        this.coordinador = coordinador;
        this.coordinador.setFrmCocina(this);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        initComponents();
        this.setLocationRelativeTo(null);
        pnlComandas.revalidate();
        pnlComandas.repaint();
        PnlScroll.getVerticalScrollBar().setUnitIncrement(25);
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFondo = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblPediddosPendientes = new javax.swing.JLabel();
        PnlScroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnlComandas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1104, 748));
        setMinimumSize(new java.awt.Dimension(1104, 748));

        PnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        panHeader.setBackground(new java.awt.Color(255, 202, 102));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_header.png"))); // NOI18N

        lblEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setText("Empleado X");

        btnCerrarSesion.setBackground(new java.awt.Color(213, 210, 203));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(lblEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(18, 18, 18))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpleado)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        lblPediddosPendientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPediddosPendientes.setForeground(new java.awt.Color(204, 204, 204));
        lblPediddosPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPediddosPendientes.setText("Pedidos Pendientes");

        javax.swing.GroupLayout pnlComandasLayout = new javax.swing.GroupLayout(pnlComandas);
        pnlComandas.setLayout(pnlComandasLayout);
        pnlComandasLayout.setHorizontalGroup(
            pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        pnlComandasLayout.setVerticalGroup(
            pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComandas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComandas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PnlScroll.setViewportView(jPanel1);

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPediddosPendientes))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPediddosPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        coordinador.cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JScrollPane PnlScroll;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblPediddosPendientes;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel pnlComandas;
    // End of variables declaration//GEN-END:variables

    public void mostrarCoamndasPendientes(List<ComandaDTO> comandas){
        pnlComandas.removeAll();
        for (ComandaDTO c : comandas) {
                pnlComandas.add(new FrmPantallaCocina.ComandaCard(c));
                pnlComandas.add(Box.createVerticalStrut(10));
            }
    }
    
    
    
    
    
    
    public class ComandaCard extends JPanel {
    private String encabezado;
    private String estado;
    private JButton btnAccion;

    private final Color COLOR_NARANJA = new Color(242, 172, 81);
    private final Color COLOR_GRIS_FONDO = new Color(230, 230, 230);
    private final Color COLOR_TEXTO = new Color(51, 51, 51);

    public ComandaCard(ComandaDTO comanda) {
        this.encabezado = "MESA: " +comanda.getNumMesa() + " | "+comanda.getNombreCliente();
        this.estado = comanda.getEstado().name();
        
        setOpaque(false);
        setLayout(new BorderLayout());
        setBorder(BorderFactory.createEmptyBorder(0, 0, 10, 0)); 

        
        JPanel panelHeader = new JPanel(new BorderLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(COLOR_NARANJA);
                
                g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight() + 10, 15, 15));
                g2.dispose();
            }
        };
        panelHeader.setOpaque(false);
        panelHeader.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));

        JLabel lblTitulo = new JLabel(encabezado);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 16));
        lblTitulo.setForeground(COLOR_TEXTO);

        JLabel lblEstado = new JLabel(estado);
        lblEstado.setFont(new Font("Arial", Font.BOLD, 16));
        lblEstado.setForeground(COLOR_TEXTO);

        panelHeader.add(lblTitulo, BorderLayout.WEST);
        panelHeader.add(lblEstado, BorderLayout.EAST);

        JPanel panelCuerpo = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(COLOR_GRIS_FONDO);
                g2.fill(new RoundRectangle2D.Float(0, -10, getWidth(), getHeight() + 10, 15, 15));
                g2.dispose();
            }
        };
        panelCuerpo.setOpaque(false);
        panelCuerpo.setLayout(new BorderLayout());
        panelCuerpo.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JPanel panelProductos = new JPanel();
        panelProductos.setOpaque(false);
        panelProductos.setLayout(new BoxLayout(panelProductos, BoxLayout.Y_AXIS));

        for (PedidoDTO ped : comanda.getPedidos()) {
            JLabel lblPedido = new JLabel();

                String texto = "• " + ped.getNombreProducto();

                if (ped.getDescripcion() != null
                        && !ped.getDescripcion().trim().isEmpty()) {

                    texto += " (" + ped.getDescripcion() + ")";
                }
            lblPedido.setFont(new Font("Arial", Font.PLAIN, 13));
            lblPedido.setForeground(COLOR_TEXTO);
            lblPedido.setAlignmentX(Component.LEFT_ALIGNMENT);
            panelProductos.add(lblPedido);
            panelProductos.add(Box.createVerticalStrut(5));
        }
        panelCuerpo.add(panelProductos, BorderLayout.CENTER);

        // Botón "Empezar pedido"
        btnAccion = new JButton("Empezar pedido");
        btnAccion.setBackground(COLOR_NARANJA);
        btnAccion.setForeground(Color.WHITE);
        btnAccion.setFont(new Font("Arial", Font.BOLD, 12));
        btnAccion.setFocusPainted(false);
        btnAccion.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        
        // Contenedor para alinear el botón a la derecha
        JPanel panelBoton = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        panelBoton.setOpaque(false);
        panelBoton.add(btnAccion);
        
        panelCuerpo.add(panelBoton, BorderLayout.SOUTH);

        // Agregar secciones al panel principal
        add(panelHeader, BorderLayout.NORTH);
        add(panelCuerpo, BorderLayout.CENTER);
    }

    public JButton getBtnAccion() {
        return btnAccion;
    }
}
}
