/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import coordinador.CoordinadorInterfaces;
import dtos.ComandaDTO;
import dtos.IngredienteEnProductoDTO;
import dtos.PedidoDTO;
import dtos.ProductoDTO;
import enums.EstadoPedidoDTO;
import enums.TipoProductoDTO;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author Dishup
 */
public final class FrmProductos extends javax.swing.JFrame {

    private CoordinadorInterfaces coordinador;

    private boolean esEdicion = false;
    private ComandaDTO comandaEdicion;
    private ComandaDTO comandaActual;

    private Integer numMesa;
    private String nombreCliente;

    /**
     * Creates new form FrmPantallaComandas
     *
     * @param coor
     */
    public FrmProductos(CoordinadorInterfaces coor) {
        this.coordinador = coor;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

        // CONFIGURACIÓN pnlPedidos
        pnlPedidos.setLayout(new BoxLayout(pnlPedidos, BoxLayout.Y_AXIS));
        pnlPedidos.setBackground(new Color(217, 217, 217));

        // IMPORTANTE: Liberar el tamaño para que crezca con los pedidos
        pnlPedidos.setPreferredSize(null);

        // Asegurar que el scroll sepa quién es su contenido
        scrollPedidos.setViewportView(pnlPedidos);
        scrollPedidos.setBorder(null); // Para que se vea limpio como en tu foto

        scrollPedidos.setVerticalScrollBarPolicy(
                javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
        );

        // PRODUCTOS (Se ve bien)
        panProductos.setLayout(new GridLayout(0, 4, 10, 15));
        JPanel contenedorAuxiliar = new JPanel(new FlowLayout(FlowLayout.LEFT));
        contenedorAuxiliar.setBackground(Color.WHITE);
        contenedorAuxiliar.add(panProductos);
        jScrollPane2.setViewportView(contenedorAuxiliar);

        panPrincipal.setFocusable(true);

        // CARGA INICIAL
        cargarCBX_TipoProducto();
        cbxTipoProducto.setSelectedItem(TipoProductoDTO.BEBIDA);
        cargarProductosPorTipo(TipoProductoDTO.BEBIDA);

        // OBLIGATORIO: Esto asegura que el panel gris use todo el espacio disponible
        pnlContenedorPedidos.revalidate();
        pnlContenedorPedidos.repaint();
        coordinador.setFrmProductos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        panPrincipal = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        pnlTituloPedidos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscador = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        panProductos = new javax.swing.JPanel();
        cbxTipoProducto = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        pnlContenedorPedidos = new javax.swing.JPanel();
        scrollPedidos = new javax.swing.JScrollPane();
        pnlPedidos = new javax.swing.JPanel();
        pnlBoton = new javax.swing.JPanel();
        btnEnviarAComanda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FrameProductos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panPrincipalMousePressed(evt);
            }
        });

        panHeader.setBackground(new java.awt.Color(255, 202, 102));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_header.png"))); // NOI18N

        lblMesa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblMesa.setForeground(new java.awt.Color(117, 83, 22));
        lblMesa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMesa.setText("MESA 1");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(117, 83, 22));
        jLabel3.setText("REGISTRO DE PEDIDO");

        lblCliente.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(117, 83, 22));
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCliente.setText("CLIENTE 1");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panHeaderLayout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(jLabel3)
                    .addContainerGap(552, Short.MAX_VALUE)))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panHeaderLayout.createSequentialGroup()
                        .addComponent(lblMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCliente))
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(24, 24, 24)))
        );

        pnlTituloPedidos.setBackground(new java.awt.Color(217, 217, 217));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PEDIDOS");

        jSeparator1.setForeground(new java.awt.Color(163, 163, 163));

        javax.swing.GroupLayout pnlTituloPedidosLayout = new javax.swing.GroupLayout(pnlTituloPedidos);
        pnlTituloPedidos.setLayout(pnlTituloPedidosLayout);
        pnlTituloPedidosLayout.setHorizontalGroup(
            pnlTituloPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloPedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
            .addGroup(pnlTituloPedidosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloPedidosLayout.setVerticalGroup(
            pnlTituloPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloPedidosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBuscador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscador.setText("Buscar");
        txtBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusLost(evt);
            }
        });
        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPane2MousePressed(evt);
            }
        });

        panProductos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panProductosLayout = new javax.swing.GroupLayout(panProductos);
        panProductos.setLayout(panProductosLayout);
        panProductosLayout.setHorizontalGroup(
            panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        panProductosLayout.setVerticalGroup(
            panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panProductos);

        cbxTipoProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        cbxTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoProductoActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(44, 44, 44));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        pnlContenedorPedidos.setLayout(new java.awt.BorderLayout());

        scrollPedidos.setBackground(new java.awt.Color(217, 217, 217));
        scrollPedidos.setBorder(null);
        scrollPedidos.setPreferredSize(new java.awt.Dimension(200, 200));

        pnlPedidos.setBackground(new java.awt.Color(217, 217, 217));
        pnlPedidos.setLayout(new javax.swing.BoxLayout(pnlPedidos, javax.swing.BoxLayout.Y_AXIS));
        scrollPedidos.setViewportView(pnlPedidos);

        pnlContenedorPedidos.add(scrollPedidos, java.awt.BorderLayout.CENTER);

        pnlBoton.setBackground(new java.awt.Color(217, 217, 217));
        pnlBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        btnEnviarAComanda.setBackground(new java.awt.Color(44, 44, 44));
        btnEnviarAComanda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnviarAComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarAComanda.setText("Enviar a comanda");
        btnEnviarAComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarAComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonLayout = new javax.swing.GroupLayout(pnlBoton);
        pnlBoton.setLayout(pnlBotonLayout);
        pnlBotonLayout.setHorizontalGroup(
            pnlBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnEnviarAComanda)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlBotonLayout.setVerticalGroup(
            pnlBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnEnviarAComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pnlContenedorPedidos.add(pnlBoton, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTituloPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedorPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlTituloPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtras)
                        .addGap(42, 42, 42))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlContenedorPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jScrollPane3.setViewportView(panPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbxTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoProductoActionPerformed
        refrescarProductosPorCategoria();
    }//GEN-LAST:event_cbxTipoProductoActionPerformed

    private void txtBuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusGained
        txtBuscador.setText("");
    }//GEN-LAST:event_txtBuscadorFocusGained

    private void txtBuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusLost
        if (txtBuscador.getText().isEmpty()) {
            txtBuscador.setText("Buscar...");
            txtBuscador.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtBuscadorFocusLost

    private void panPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panPrincipalMousePressed
        txtBuscador.transferFocus();
    }//GEN-LAST:event_panPrincipalMousePressed

    private void jScrollPane2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MousePressed
        txtBuscador.transferFocus();
    }//GEN-LAST:event_jScrollPane2MousePressed

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        String[] partes = lblCliente.getText().trim().split(" ");
        coordinador.frmProductosAFrmCliente(partes[1], numMesa);
        this.dispose();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        String textoBusqueda = txtBuscador.getText().trim().toLowerCase();
        TipoProductoDTO tipo = (TipoProductoDTO) cbxTipoProducto.getSelectedItem();

        if (textoBusqueda.isEmpty() || textoBusqueda.equals("buscar...")) {
            refrescarProductosPorCategoria();
            return;
        }

        filtrarProductos(textoBusqueda, tipo);
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void btnEnviarAComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarAComandaActionPerformed
//        if (comandaActual != null) {
//            coordinador.abrirResumenAgregarPedido(comandaActual);
//        } else {
//            coordinador.abrirResumenComanda(this, numMesa, nombreCliente);
//        }

        if (esEdicion) {
            coordinador.abrirResumenEditarComanda(comandaEdicion);
        } else {
            if (!comandaTemporalVacia()) {
                if (comandaActual != null) {
                    coordinador.abrirResumenAgregarPedido(comandaActual);
                } else {
                    coordinador.abrirResumenComanda(this, numMesa, nombreCliente);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "No has agregado pedidos aún", "Aviso",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEnviarAComandaActionPerformed

    private JPanel crearCardProducto(ProductoDTO producto) {

        JPanel card = new JPanel();

        card.setFocusable(false);

        card.setLayout(new BorderLayout());
        card.setPreferredSize(new Dimension(150, 180));
        card.setBackground(Color.decode("#FFE3AC"));
        card.setBorder(BorderFactory.createLineBorder(Color.decode("#767676"), 5, true));

        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                if (producto.isDisponible()) {
                    card.setBackground(Color.decode("#DCB15E"));
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (producto.isDisponible()) {
                    card.setBackground(Color.decode("#FFE3AC"));
                }
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                txtBuscador.transferFocus();

                if (producto.isDisponible()) {
                    productoSeleccionado(producto);
                }
            }

        });

        JLabel lblImagen = new JLabel() {
            @Override
            public void paint(Graphics g) {
                super.paint(g);

                if (!producto.isDisponible()) {
                    Graphics2D g2 = (Graphics2D) g;

                    g2.setColor(new Color(0, 0, 0, 120));
                    g2.fillRect(0, 0, getWidth(), getHeight());

                    g2.setColor(Color.DARK_GRAY);
                    g2.setStroke(new BasicStroke(3));
                    g2.drawLine(0, 0, getWidth(), getHeight());
                }
            }
        };

        if (producto.getUrlImagen() != null) {
            try {
                ImageIcon icon;

                if (producto.getUrlImagen().startsWith("http")) {
                    // Imagen desde internet
                    icon = new ImageIcon(new java.net.URL(producto.getUrlImagen()));
                } else {
                    // Imagen local
                    icon = new ImageIcon(getClass().getResource(producto.getUrlImagen()));
                }

                Image img = icon.getImage().getScaledInstance(120, 100, Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(img));

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        lblImagen.setHorizontalAlignment(JLabel.CENTER);

        JLabel lblNombre = new JLabel(producto.getNombre());
        lblNombre.setHorizontalAlignment(JLabel.CENTER);
        lblNombre.setFont(new Font("Trebuchet MS", Font.PLAIN, 16));

        card.add(lblImagen, BorderLayout.CENTER);
        card.add(lblNombre, BorderLayout.SOUTH);

        return card;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviarAComanda;
    private javax.swing.JComboBox<enums.TipoProductoDTO> cbxTipoProducto;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panProductos;
    private javax.swing.JPanel pnlBoton;
    private javax.swing.JPanel pnlContenedorPedidos;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JPanel pnlTituloPedidos;
    private javax.swing.JScrollPane scrollPedidos;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables

    private void cargarCBX_TipoProducto() {
        cbxTipoProducto.removeAllItems();

        for (TipoProductoDTO tipo : TipoProductoDTO.values()) {
            cbxTipoProducto.addItem(tipo);
        }
    }

    public void setMesaAndCliente(Integer numMesa, String cliente) {
        this.numMesa = numMesa;
        this.nombreCliente = cliente;

        lblMesa.setText("MESA " + numMesa);
        lblCliente.setText("CLIENTE: " + cliente);
    }

    public void cargarProductosPorTipo(TipoProductoDTO tipo) {
        panProductos.removeAll();

        List<ProductoDTO> productos = coordinador.obtenerProductosParaUI(tipo);

        for (ProductoDTO producto : productos) {

            if (producto.getTipo().name().equals(tipo.name())) {
                JPanel card = crearCardProducto(producto);
                panProductos.add(card);
            }
        }

        panProductos.revalidate();
        panProductos.repaint();
    }

    public void filtrarProductos(String filtro, TipoProductoDTO tipo) {
        panProductos.removeAll();
        int productosEncontrados = 0;

        TipoProductoDTO tipoActual = (TipoProductoDTO) cbxTipoProducto.getSelectedItem();
        List<ProductoDTO> productos = coordinador.obtenerProductosParaUI(tipo);

        for (ProductoDTO producto : productos) {
            if (producto.getTipo().equals(tipoActual)
                    && producto.getNombre().toLowerCase().contains(filtro)) {

                JPanel card = crearCardProducto(producto);
                panProductos.add(card);
                productosEncontrados++;
            }
        }

        if (productosEncontrados == 0) {
            JLabel lblVacio = new JLabel("No se encontraron coincidencias para: " + filtro);
            panProductos.add(lblVacio);
        }

        panProductos.revalidate();
        panProductos.repaint();
    }

    private void refrescarProductosPorCategoria() {
        TipoProductoDTO tipo = (TipoProductoDTO) cbxTipoProducto.getSelectedItem();
        cargarProductosPorTipo(tipo);
    }

    private void productoSeleccionado(ProductoDTO producto) {
        List<IngredienteEnProductoDTO> removibles = coordinador.obtenerIngredientesRemovibles(producto.getId());
        coordinador.abrirPersonalizacionProducto(this, producto, removibles);
    }

    public void agregarPedidoVisual(PedidoDTO pedido, ComandaDTO comandaOrigen) {
        pnlPedidos.setLayout(new BoxLayout(pnlPedidos, BoxLayout.Y_AXIS));
        for (Component c : pnlPedidos.getComponents()) {
            if (c instanceof Box.Filler) {
                pnlPedidos.remove(c);
            }
        }

        JPanel item = new JPanel();
        item.setLayout(new BoxLayout(item, BoxLayout.Y_AXIS));
        item.setOpaque(false);
        item.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Si viene de una comanda (edición) borde naranja, si es nuevo borde gris
        Border lineaBorde = (comandaOrigen != null)
                ? BorderFactory.createLineBorder(Color.decode("#E58343"), 2)
                : BorderFactory.createLineBorder(new Color(160, 160, 160), 2);

        item.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createEmptyBorder(8, 18, 8, 18),
                BorderFactory.createCompoundBorder(
                        lineaBorde,
                        BorderFactory.createEmptyBorder(12, 12, 12, 12)
                )
        ));

        // HEADER
        JPanel header = new JPanel(new BorderLayout());
        header.setOpaque(false);
        header.setMaximumSize(new Dimension(Integer.MAX_VALUE, 25));
        header.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel lblNombre = new JLabel(pedido.getNombreProducto().toUpperCase());
        lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 14));
        header.add(lblNombre, BorderLayout.WEST);

        JLabel btnX = null;

        if (pedido.getEstado() == null || pedido.getEstado() == EstadoPedidoDTO.PENDIENTE) {

            btnX = new JLabel("X");

            btnX.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnX.setForeground(Color.decode("#000000"));

            btnX.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {

                    int confirmacion = JOptionPane.showConfirmDialog(
                            FrmProductos.this,
                            "¿Quitar \"" + pedido.getNombreProducto() + "\" del pedido?",
                            "Confirmar eliminación",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE
                    );

                    if (confirmacion != JOptionPane.YES_OPTION) {
                        return;
                    }

                    if (comandaOrigen != null) {
                        comandaOrigen.getPedidos().remove(pedido);
                    } else {
                        coordinador.eliminarPedidoTemporal(pedido);
                    }

                    pnlPedidos.remove(item);

                    pnlPedidos.revalidate();
                    pnlPedidos.repaint();
                }
            });

            header.add(btnX, BorderLayout.EAST);
        }

        // DETALLES
        JTextArea txtLista = new JTextArea();
        txtLista.setEditable(false);
        txtLista.setBackground(new Color(242, 242, 242));
        txtLista.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtLista.setLineWrap(true);
        txtLista.setWrapStyleWord(true);
        String desc = (pedido.getDescripcion() != null && !pedido.getDescripcion().isEmpty())
                ? pedido.getDescripcion().replace(", ", "\n• ")
                : "";
        txtLista.setText("• " + desc);
        txtLista.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtLista.setAlignmentX(Component.LEFT_ALIGNMENT);

        // Doble clic
        item.setCursor(new Cursor(Cursor.HAND_CURSOR));
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2  && pedido.getEstado() == EstadoPedidoDTO.PENDIENTE || pedido.getEstado() == null) {
                    coordinador.abrirModificacionPedidoExistente(
                            FrmProductos.this, pedido, comandaOrigen, item, txtLista
                    );
                }
            }
        });

        item.add(header);
        item.add(Box.createVerticalStrut(10));
        item.add(txtLista);
        item.setMaximumSize(new Dimension(Integer.MAX_VALUE, item.getPreferredSize().height));

        pnlPedidos.add(item);
        pnlPedidos.add(Box.createVerticalGlue());
        pnlPedidos.revalidate();
        pnlPedidos.repaint();

        SwingUtilities.invokeLater(()
                -> scrollPedidos.getVerticalScrollBar().setValue(
                        scrollPedidos.getVerticalScrollBar().getMaximum()
                )
        );
    }

    public void cargarPedidosExistentes(ComandaDTO comanda) {

        this.comandaActual = comanda;

        for (PedidoDTO pedido : comanda.getPedidos()) {
            agregarPedidoBloqueado(pedido);
        }
    }

    public void agregarPedidoBloqueado(PedidoDTO pedido) {

        pnlPedidos.setLayout(new BoxLayout(pnlPedidos, BoxLayout.Y_AXIS));

        for (Component c : pnlPedidos.getComponents()) {
            if (c instanceof Box.Filler) {
                pnlPedidos.remove(c);
            }
        }

        JPanel item = new JPanel();
        item.setLayout(new BoxLayout(item, BoxLayout.Y_AXIS));

        item.setBackground(new Color(235, 235, 235));
        item.setOpaque(false);

        Border margenGrisExterior = BorderFactory.createEmptyBorder(8, 18, 8, 18);

        Border lineaGris = BorderFactory.createLineBorder(Color.decode("#E58343"));

        Border margenInteriorBlanco = BorderFactory.createEmptyBorder(12, 12, 12, 12);

        item.setBorder(BorderFactory.createCompoundBorder(
                margenGrisExterior,
                BorderFactory.createCompoundBorder(
                        lineaGris,
                        margenInteriorBlanco
                )
        ));

        item.setAlignmentX(Component.CENTER_ALIGNMENT);

        // HEADER
        JPanel header = new JPanel(new BorderLayout());
        header.setOpaque(false);
        header.setMaximumSize(new Dimension(Integer.MAX_VALUE, 25));
        header.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel lblNombre = new JLabel(pedido.getNombreProducto().toUpperCase());

        lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblNombre.setForeground(new Color(80, 80, 80));

        header.add(lblNombre, BorderLayout.WEST);

        // DETALLES
        JTextArea txtLista = new JTextArea();

        txtLista.setEditable(false);

        txtLista.setBackground(new Color(242, 242, 242));

        txtLista.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        txtLista.setLineWrap(true);
        txtLista.setWrapStyleWord(true);

        String detallesFormateados
                = pedido.getDescripcion().replace(", ", "\n• ");

        txtLista.setText("• " + detallesFormateados);

        txtLista.setBorder(
                BorderFactory.createEmptyBorder(10, 10, 10, 10)
        );

        txtLista.setAlignmentX(Component.LEFT_ALIGNMENT);

        // ENSAMBLAJE
        item.add(header);
        item.add(Box.createVerticalStrut(10));
        item.add(txtLista);

        item.setMaximumSize(
                new Dimension(
                        Integer.MAX_VALUE,
                        item.getPreferredSize().height
                )
        );

        pnlPedidos.add(item);
        pnlPedidos.add(Box.createVerticalGlue());

        pnlPedidos.revalidate();
        pnlPedidos.repaint();
    }

    public void setModoNuevo() {
        this.esEdicion = false;
        this.comandaActual = null;
        pnlPedidos.removeAll();
    }

    public void setModoEdicion(ComandaDTO comanda) {
        this.esEdicion = true;
        this.comandaEdicion = comanda;
        this.comandaActual = comanda;
        coordinador.limpiarComandaTemporal(); // nuevo método en coordinador
        pnlPedidos.removeAll();
        for (PedidoDTO pedido : comanda.getPedidos()) {
            agregarPedidoVisual(pedido, comanda);
        }
        pnlPedidos.revalidate();
        pnlPedidos.repaint();
    }

    public void cargarPedidosEditables(ComandaDTO comanda) {
        this.comandaActual = comanda;
        pnlPedidos.removeAll();

        for (PedidoDTO pedido : comanda.getPedidos()) {
            agregarPedidoVisual(pedido, comanda);
        }

        pnlPedidos.revalidate();
        pnlPedidos.repaint();
    }

    private boolean comandaTemporalVacia() {
        return coordinador.getComandaTemporal().isEmpty();
    }

    public void refrescarPedidos() {
        pnlPedidos.removeAll();

        List<PedidoDTO> pedidos = coordinador.getComandaTemporal();

        for (PedidoDTO pedido : pedidos) {
            agregarPedidoVisual(pedido, null);
        }

        pnlPedidos.revalidate();
        pnlPedidos.repaint();
    }
}
