/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.AdministrarMesas;

import coordinador.CoordinadorInterfaces;
import dtos.EmpleadoDTO;
import dtos.MesaDTO;
import excepciones.MesasException;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandra Leal Armenta, 262719
 */
public class FrmAsignarMesas extends javax.swing.JFrame {
    
    private final EmpleadoDTO mesero;
    private final EmpleadoDTO gerente;
    private final CoordinadorInterfaces coordinador;
    private final ImageIcon iconoOff = new ImageIcon(getClass().getResource("/img/checks/check_off.png"));
    private final ImageIcon iconoOn = new ImageIcon(getClass().getResource("/img/checks/check_on.png"));
    private boolean huboCambios = false;
    
    public FrmAsignarMesas(EmpleadoDTO mesero, EmpleadoDTO gerente, CoordinadorInterfaces coordinador) {
        initComponents();
        this.mesero = mesero;
        this.gerente = gerente;
        this.coordinador = coordinador;

        this.setLocationRelativeTo(null);
        
        panAsignadas.setLayout( new BoxLayout( panAsignadas, BoxLayout.Y_AXIS ));
        panDisponibles.setLayout( new BoxLayout( panDisponibles, BoxLayout.Y_AXIS ) );
        setTextos();
        lblEmpleado.setText(gerente.getNombres()+" "+gerente.getApellidoPaterno());
        refrescarMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panComponentes = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panHeader = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblAsignadas = new javax.swing.JLabel();
        lblDisponibles = new javax.swing.JLabel();
        scrollMesasAsignadas = new javax.swing.JScrollPane();
        panAsignadas = new javax.swing.JPanel();
        scrollDisponibles = new javax.swing.JScrollPane();
        panDisponibles = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panComponentes.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Yu Gothic Medium", 0, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Mesero usuario: nombres");

        panHeader.setBackground(new java.awt.Color(255, 202, 102));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_header.png"))); // NOI18N

        lblEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setText("nombre Gerente");

        btnCerrarSesion.setBackground(new java.awt.Color(213, 210, 203));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(lblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addGap(18, 18, 18))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpleado)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        lblAsignadas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAsignadas.setText("Mesas asignadas:");

        lblDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDisponibles.setText("Mesas disponibles:");

        scrollMesasAsignadas.setBackground(new java.awt.Color(255, 255, 255));
        scrollMesasAsignadas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollMesasAsignadas.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panAsignadas.setBackground(new java.awt.Color(255, 255, 255));
        panAsignadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panAsignadasLayout = new javax.swing.GroupLayout(panAsignadas);
        panAsignadas.setLayout(panAsignadasLayout);
        panAsignadasLayout.setHorizontalGroup(
            panAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        panAsignadasLayout.setVerticalGroup(
            panAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        scrollMesasAsignadas.setViewportView(panAsignadas);

        scrollDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        scrollDisponibles.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDisponibles.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        panDisponibles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panDisponiblesLayout = new javax.swing.GroupLayout(panDisponibles);
        panDisponibles.setLayout(panDisponiblesLayout);
        panDisponiblesLayout.setHorizontalGroup(
            panDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        panDisponiblesLayout.setVerticalGroup(
            panDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        scrollDisponibles.setViewportView(panDisponibles);

        btnCancelar.setBackground(new java.awt.Color(169, 42, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(99, 143, 77));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar cambios");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panComponentesLayout = new javax.swing.GroupLayout(panComponentes);
        panComponentes.setLayout(panComponentesLayout);
        panComponentesLayout.setHorizontalGroup(
            panComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComponentesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComponentesLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(159, 159, 159))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComponentesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAsignadas)
                    .addComponent(scrollMesasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisponibles)
                    .addComponent(scrollDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComponentesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnConfirmar)
                .addGap(43, 43, 43))
        );
        panComponentesLayout.setVerticalGroup(
            panComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComponentesLayout.createSequentialGroup()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panComponentesLayout.createSequentialGroup()
                        .addComponent(lblDisponibles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollDisponibles))
                    .addGroup(panComponentesLayout.createSequentialGroup()
                        .addComponent(lblAsignadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollMesasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(panComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (!huboCambios) {
            coordinador.pantallaMesas(gerente);
            this.dispose();
            return;
        }

        int opcion = JOptionPane.showConfirmDialog( this, "¿Esta seguro de cancelar la operación?", "CONFIRMACION", JOptionPane.YES_NO_OPTION );

        if (opcion == JOptionPane.YES_OPTION) {
            coordinador.pantallaMesas(gerente);
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro de confirmar esta accion?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        
        if(opcion == JOptionPane.YES_OPTION){
            List<MesaDTO> mesasAsignar = new ArrayList<>();
            List<MesaDTO> mesasDesasignar = new ArrayList<>();
            
            Component[] checksDisponibles = panDisponibles.getComponents();
            for (Component componente: checksDisponibles) {

                JCheckBox check = (JCheckBox) componente;
                if (check.isSelected()) {
                    MesaDTO mesa = (MesaDTO)check.getClientProperty("mesa");
                    mesasAsignar.add(mesa);
                }
            }
            
            Component[] checksAsignadas = panAsignadas.getComponents();
            for (Component componente: checksAsignadas) {
                JCheckBox check = (JCheckBox) componente;
                
                if (!check.isSelected()) {
                    MesaDTO mesa = (MesaDTO)check.getClientProperty("mesa");
                    mesasDesasignar.add(mesa);
                } 
            }
            
            try {
                coordinador.actualizarMesasDeMesero(mesasAsignar, mesasDesasignar, mesero);
                
                JOptionPane.showMessageDialog(this, "Las mesas se actualizaron correctamente", "Mesas Asignadas", JOptionPane.INFORMATION_MESSAGE);
                coordinador.pantallaMesas(gerente);
                this.dispose();
            } catch (MesasException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        coordinador.cerrarSesion();
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblAsignadas;
    private javax.swing.JLabel lblDisponibles;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panAsignadas;
    private javax.swing.JPanel panComponentes;
    private javax.swing.JPanel panDisponibles;
    private javax.swing.JPanel panHeader;
    private javax.swing.JScrollPane scrollDisponibles;
    private javax.swing.JScrollPane scrollMesasAsignadas;
    // End of variables declaration//GEN-END:variables

    public void refrescarMesas(){
        try {
            List<MesaDTO> listaMesero = coordinador.obtenerMesasDelMesero(mesero);
            List<MesaDTO> listaDisponibles = coordinador.obtenerMesasDisponibles();
            cargarMesasMesero(listaMesero);
            cargarMesasDisponibles(listaDisponibles);
        } catch (MesasException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void cargarMesasMesero(List<MesaDTO> lista){
        panAsignadas.removeAll();

        for (MesaDTO mesa : lista) {

            JCheckBox checkMesa = new JCheckBox(
                    "Mesa " + mesa.getNumeroMesa()
            );

            checkMesa.setSelected(true);
            
            checkMesa.setIcon(iconoOff);
            
            checkMesa.setSelectedIcon(iconoOn);

            checkMesa.putClientProperty("mesa", mesa);

            checkMesa.setMaximumSize(
                    new Dimension(Integer.MAX_VALUE, 40)
            );
            
            aplicarEstiloCheck(checkMesa);
            
            checkMesa.addActionListener(e -> {
                aplicarEstiloCheck(checkMesa);
                huboCambios = true;
            });

            panAsignadas.add(checkMesa);
        }

        panAsignadas.revalidate();
        panAsignadas.repaint();
    }
    
    public void cargarMesasDisponibles(List<MesaDTO> lista) {

        panDisponibles.removeAll();

        for (MesaDTO mesa : lista) {

            JCheckBox checkMesa = new JCheckBox(
                    "Mesa " + mesa.getNumeroMesa()
            );

            checkMesa.setSelected(false);

            checkMesa.setIcon(iconoOff);

            checkMesa.setSelectedIcon(iconoOn);

            checkMesa.putClientProperty("mesa", mesa);

            checkMesa.setMaximumSize(
                    new Dimension(Integer.MAX_VALUE, 40)
            );
            
            aplicarEstiloCheck(checkMesa);
            
            checkMesa.addActionListener(e -> {
                aplicarEstiloCheck(checkMesa);
                huboCambios = true;
            });

            panDisponibles.add(checkMesa);
        }

        panDisponibles.revalidate();
        panDisponibles.repaint();
    }
    
    private void aplicarEstiloCheck(JCheckBox check) {
        Color morado = new Color(68, 59, 85);

        check.setFont(
                new Font("Segoe UI", Font.BOLD, 16)
        );

        check.setFocusPainted(false);

        check.setOpaque(true);

        check.setBackground(Color.WHITE);
    }
    
    public void setTextos(){
        lblTitle.setText("Mesero "+mesero.getUser()+": "+mesero.getNombres());
    }
}
